// Code generated by go generate; DO NOT EDIT.

package zog

import "github.com/Oudwins/zog/zconst"

func (s *AnySchema) Meta(k zconst.ZogMetaKey, v any) *AnySchema {
	GlobalMetaRegistry.Set(s, k, v)
	return s
}

func (s *AnySchema) MetaFunc(f func() SchemaMetadata) *AnySchema {
	m := f()
	GlobalMetaRegistry.SetCopy(s, m)
	return s
}

func (s *AnySchema) Registry(r ZogMetaRegistry, k zconst.ZogMetaKey, v any) *AnySchema {
	r.Set(s, k, v)
	return s
}

func (s *AnySchema) RegistryFunc(f func() (ZogMetaRegistry, SchemaMetadata)) *AnySchema {
	r, m := f()
	r.SetCopy(s, m)
	return s
}

func (s *BoolSchema[T]) Meta(k zconst.ZogMetaKey, v any) *BoolSchema[T] {
	GlobalMetaRegistry.Set(s, k, v)
	return s
}

func (s *BoolSchema[T]) MetaFunc(f func() SchemaMetadata) *BoolSchema[T] {
	m := f()
	GlobalMetaRegistry.SetCopy(s, m)
	return s
}

func (s *BoolSchema[T]) Registry(r ZogMetaRegistry, k zconst.ZogMetaKey, v any) *BoolSchema[T] {
	r.Set(s, k, v)
	return s
}

func (s *BoolSchema[T]) RegistryFunc(f func() (ZogMetaRegistry, SchemaMetadata)) *BoolSchema[T] {
	r, m := f()
	r.SetCopy(s, m)
	return s
}

func (s *BoxedSchema[B, T]) Meta(k zconst.ZogMetaKey, v any) *BoxedSchema[B, T] {
	GlobalMetaRegistry.Set(s, k, v)
	return s
}

func (s *BoxedSchema[B, T]) MetaFunc(f func() SchemaMetadata) *BoxedSchema[B, T] {
	m := f()
	GlobalMetaRegistry.SetCopy(s, m)
	return s
}

func (s *BoxedSchema[B, T]) Registry(r ZogMetaRegistry, k zconst.ZogMetaKey, v any) *BoxedSchema[B, T] {
	r.Set(s, k, v)
	return s
}

func (s *BoxedSchema[B, T]) RegistryFunc(f func() (ZogMetaRegistry, SchemaMetadata)) *BoxedSchema[B, T] {
	r, m := f()
	r.SetCopy(s, m)
	return s
}

func (s *CustomSchema) Meta(k zconst.ZogMetaKey, v any) *CustomSchema {
	GlobalMetaRegistry.Set(s, k, v)
	return s
}

func (s *CustomSchema) MetaFunc(f func() SchemaMetadata) *CustomSchema {
	m := f()
	GlobalMetaRegistry.SetCopy(s, m)
	return s
}

func (s *CustomSchema) Registry(r ZogMetaRegistry, k zconst.ZogMetaKey, v any) *CustomSchema {
	r.Set(s, k, v)
	return s
}

func (s *CustomSchema) RegistryFunc(f func() (ZogMetaRegistry, SchemaMetadata)) *CustomSchema {
	r, m := f()
	r.SetCopy(s, m)
	return s
}

func (s *Custom[T]) Meta(k zconst.ZogMetaKey, v any) *Custom[T] {
	GlobalMetaRegistry.Set(s, k, v)
	return s
}

func (s *Custom[T]) MetaFunc(f func() SchemaMetadata) *Custom[T] {
	m := f()
	GlobalMetaRegistry.SetCopy(s, m)
	return s
}

func (s *Custom[T]) Registry(r ZogMetaRegistry, k zconst.ZogMetaKey, v any) *Custom[T] {
	r.Set(s, k, v)
	return s
}

func (s *Custom[T]) RegistryFunc(f func() (ZogMetaRegistry, SchemaMetadata)) *Custom[T] {
	r, m := f()
	r.SetCopy(s, m)
	return s
}

func (s *MapSchema[K, V]) Meta(k zconst.ZogMetaKey, v any) *MapSchema[K, V] {
	GlobalMetaRegistry.Set(s, k, v)
	return s
}

func (s *MapSchema[K, V]) MetaFunc(f func() SchemaMetadata) *MapSchema[K, V] {
	m := f()
	GlobalMetaRegistry.SetCopy(s, m)
	return s
}

func (s *MapSchema[K, V]) Registry(r ZogMetaRegistry, k zconst.ZogMetaKey, v any) *MapSchema[K, V] {
	r.Set(s, k, v)
	return s
}

func (s *MapSchema[K, V]) RegistryFunc(f func() (ZogMetaRegistry, SchemaMetadata)) *MapSchema[K, V] {
	r, m := f()
	r.SetCopy(s, m)
	return s
}

func (s *NumberSchema[T]) Meta(k zconst.ZogMetaKey, v any) *NumberSchema[T] {
	GlobalMetaRegistry.Set(s, k, v)
	return s
}

func (s *NumberSchema[T]) MetaFunc(f func() SchemaMetadata) *NumberSchema[T] {
	m := f()
	GlobalMetaRegistry.SetCopy(s, m)
	return s
}

func (s *NumberSchema[T]) Registry(r ZogMetaRegistry, k zconst.ZogMetaKey, v any) *NumberSchema[T] {
	r.Set(s, k, v)
	return s
}

func (s *NumberSchema[T]) RegistryFunc(f func() (ZogMetaRegistry, SchemaMetadata)) *NumberSchema[T] {
	r, m := f()
	r.SetCopy(s, m)
	return s
}

func (s *PointerSchema) Meta(k zconst.ZogMetaKey, v any) *PointerSchema {
	GlobalMetaRegistry.Set(s, k, v)
	return s
}

func (s *PointerSchema) MetaFunc(f func() SchemaMetadata) *PointerSchema {
	m := f()
	GlobalMetaRegistry.SetCopy(s, m)
	return s
}

func (s *PointerSchema) Registry(r ZogMetaRegistry, k zconst.ZogMetaKey, v any) *PointerSchema {
	r.Set(s, k, v)
	return s
}

func (s *PointerSchema) RegistryFunc(f func() (ZogMetaRegistry, SchemaMetadata)) *PointerSchema {
	r, m := f()
	r.SetCopy(s, m)
	return s
}

func (s *PreprocessSchema[F, T]) Meta(k zconst.ZogMetaKey, v any) *PreprocessSchema[F, T] {
	GlobalMetaRegistry.Set(s, k, v)
	return s
}

func (s *PreprocessSchema[F, T]) MetaFunc(f func() SchemaMetadata) *PreprocessSchema[F, T] {
	m := f()
	GlobalMetaRegistry.SetCopy(s, m)
	return s
}

func (s *PreprocessSchema[F, T]) Registry(r ZogMetaRegistry, k zconst.ZogMetaKey, v any) *PreprocessSchema[F, T] {
	r.Set(s, k, v)
	return s
}

func (s *PreprocessSchema[F, T]) RegistryFunc(f func() (ZogMetaRegistry, SchemaMetadata)) *PreprocessSchema[F, T] {
	r, m := f()
	r.SetCopy(s, m)
	return s
}

func (s *SliceSchema) Meta(k zconst.ZogMetaKey, v any) *SliceSchema {
	GlobalMetaRegistry.Set(s, k, v)
	return s
}

func (s *SliceSchema) MetaFunc(f func() SchemaMetadata) *SliceSchema {
	m := f()
	GlobalMetaRegistry.SetCopy(s, m)
	return s
}

func (s *SliceSchema) Registry(r ZogMetaRegistry, k zconst.ZogMetaKey, v any) *SliceSchema {
	r.Set(s, k, v)
	return s
}

func (s *SliceSchema) RegistryFunc(f func() (ZogMetaRegistry, SchemaMetadata)) *SliceSchema {
	r, m := f()
	r.SetCopy(s, m)
	return s
}

func (s *StringSchema[T]) Meta(k zconst.ZogMetaKey, v any) *StringSchema[T] {
	GlobalMetaRegistry.Set(s, k, v)
	return s
}

func (s *StringSchema[T]) MetaFunc(f func() SchemaMetadata) *StringSchema[T] {
	m := f()
	GlobalMetaRegistry.SetCopy(s, m)
	return s
}

func (s *StringSchema[T]) Registry(r ZogMetaRegistry, k zconst.ZogMetaKey, v any) *StringSchema[T] {
	r.Set(s, k, v)
	return s
}

func (s *StringSchema[T]) RegistryFunc(f func() (ZogMetaRegistry, SchemaMetadata)) *StringSchema[T] {
	r, m := f()
	r.SetCopy(s, m)
	return s
}

func (s *StructSchema) Meta(k zconst.ZogMetaKey, v any) *StructSchema {
	GlobalMetaRegistry.Set(s, k, v)
	return s
}

func (s *StructSchema) MetaFunc(f func() SchemaMetadata) *StructSchema {
	m := f()
	GlobalMetaRegistry.SetCopy(s, m)
	return s
}

func (s *StructSchema) Registry(r ZogMetaRegistry, k zconst.ZogMetaKey, v any) *StructSchema {
	r.Set(s, k, v)
	return s
}

func (s *StructSchema) RegistryFunc(f func() (ZogMetaRegistry, SchemaMetadata)) *StructSchema {
	r, m := f()
	r.SetCopy(s, m)
	return s
}

func (s *TimeSchema) Meta(k zconst.ZogMetaKey, v any) *TimeSchema {
	GlobalMetaRegistry.Set(s, k, v)
	return s
}

func (s *TimeSchema) MetaFunc(f func() SchemaMetadata) *TimeSchema {
	m := f()
	GlobalMetaRegistry.SetCopy(s, m)
	return s
}

func (s *TimeSchema) Registry(r ZogMetaRegistry, k zconst.ZogMetaKey, v any) *TimeSchema {
	r.Set(s, k, v)
	return s
}

func (s *TimeSchema) RegistryFunc(f func() (ZogMetaRegistry, SchemaMetadata)) *TimeSchema {
	r, m := f()
	r.SetCopy(s, m)
	return s
}

func (s *lazySchema) Meta(k zconst.ZogMetaKey, v any) *lazySchema {
	GlobalMetaRegistry.Set(s, k, v)
	return s
}

func (s *lazySchema) MetaFunc(f func() SchemaMetadata) *lazySchema {
	m := f()
	GlobalMetaRegistry.SetCopy(s, m)
	return s
}

func (s *lazySchema) Registry(r ZogMetaRegistry, k zconst.ZogMetaKey, v any) *lazySchema {
	r.Set(s, k, v)
	return s
}

func (s *lazySchema) RegistryFunc(f func() (ZogMetaRegistry, SchemaMetadata)) *lazySchema {
	r, m := f()
	r.SetCopy(s, m)
	return s
}
