name: Coverage

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  coverage:
    strategy:
      matrix:
        go-version: [1.21.x, 1.22.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Test
        run: go test -race -covermode=atomic -coverprofile="profile.cov" ./...

      - name: Send Coverage
        if: matrix.os == 'ubuntu-latest' && matrix.go-version == '1.22.x'
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: profile.cov
